'use client'
import { useDashboardStore } from '@/store/dashboard.store'
import { useEffect, useState } from 'react'

const Dashboard = ({ dataToDisplay }) => {

    const { dashboardData, fetchDashboard, isLoading, error, username } = useDashboardStore()

    useEffect(() => {
        if (!username) return
        fetchDashboard(username)
    }, [username])

    return (
        <div>
            <h1>Dashboard</h1>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facere ratione assumenda architecto optio possimus, officiis dolore, facilis sed eos, sit ipsa voluptas tempora cupiditate. Ab porro assumenda delectus! Libero maiores minus, obcaecati vitae facere molestiae voluptate! Quasi.
        </div>
    )
}

export default Dashboard
